---
title: "StatsgH2Avw1118"
output: html_document
date: "2026-01-19"
editor_options: 
  chunk_output_type: console
---

Set-up
```{r}
library(dplyr)
library(broom)
```

```{r}
getwd()
#should direct to R project folder, if directed to /Code/Figure2, skip next step or redirect to /Code/Figure2
```

```{r}
setwd("Code/CodeFigure2")
getwd()
#working directory should be /Code/Figure2
```

Load data
```{r}
gH2Avstats <- read_csv("../../Data/DataFigure2/w1118gH2Av.csv")
```

```{r}
gH2Avstats <- gH2Avstats %>%
  mutate(
    Weeks = factor(Weeks, levels = c(1, 6))  # Week 1 = reference
  )

fit <- glm(
  gH2Av ~ Weeks,
  family = poisson(link = "log"),
  data = gH2Avstats
)

glm_tidy <- tidy(fit)

week6_row <- glm_tidy %>%
  filter(term == "Weeks6")

p_val <- week6_row$p.value

stars <- case_when(
  p_val < 0.001  ~ "***",
  p_val < 0.01   ~ "**",
  p_val < 0.05   ~ "*",
  TRUE           ~ "ns"
)

poisson_gH2Av <- data.frame(
  comparison = "6 Weeks",
  model = "Poisson_GLM",
  estimate_logRR = week6_row$estimate,
  p_value = p_val,
  stars = stars
)

print(poisson_gH2Av)
```

```{r}
write.csv(
  poisson_gH2Av,
  file = "../../Results/ResultsFigure2/StatsgH2AvPoisson.csv",
  row.names = FALSE
)
```
